//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApi1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        public int idCliente { get; set; }
        public Nullable<int> ci { get; set; }
        public string nombre { get; set; }
        public string apellidos { get; set; }
        public string edad { get; set; }
        public string Nacionalidad { get; set; }
        public Nullable<int> estado { get; set; }
    }
}
